import Head from 'next/head';
import styles from '../styles/Home.module.css';
import styled, { css } from 'styled-components';

const StyledHeader = styled.h1`
  padding: 1rem;
  font-weight: 600;
  text-align: center;
  ${props => {
    return css`
      background-color: ${props.theme.colors.bgColor};
      color: ${props.theme.colors.color};
    `;
  }};
`;

export default function Container(props: { children: any }) {
  const { children } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Products Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledHeader>react-products v1.00</StyledHeader>

      {children}

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>Alessandra Canuto</span>
      </footer>
    </div>
  );
}
